### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by wassupdee** [wassupdee/RUNTEQ_portfolio#114]
## 各種情報
サービス名：Re-Connect
サービスURL：https://powerful-sands-04341-a27c5520cc0b.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] 新規登録
- [x] ログイン
- [ ] パスワードリセット
- [ ] メールアドレス変更
- [x] OpenAI APIによる、メッセージ提案
- [x] LINE通知
- [x] 連絡先登録

## READMEレビュー時から変更した機能
- パスワードリセット（本リリースで実装）
- メールアドレス変更（本リリースで実装）

### TOPページ
[![Image from Gyazo](https://i.gyazo.com/a2f8236df346a6a2916beb11ea7113b8.jpg)](https://gyazo.com/a2f8236df346a6a2916beb11ea7113b8)

### AI提案サービス
[![Image from Gyazo](https://i.gyazo.com/61e07acc8ed808cb5a469cde78caed25.gif)](https://gyazo.com/61e07acc8ed808cb5a469cde78caed25)
[![Image from Gyazo](https://i.gyazo.com/943bdb33604820a83023e8d46e0da3c8.png)](https://gyazo.com/943bdb33604820a83023e8d46e0da3c8)

### 大切な日の通知サービス
[![Image from Gyazo](https://i.gyazo.com/08970aa8bcc4a150d5722d89030881fd.png)](https://gyazo.com/08970aa8bcc4a150d5722d89030881fd)

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。

**Comment by wassupdee** [comment]
ご確認どうもありがとうございます！
がんばります！
