### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by wassupdee** [wassupdee/RUNTEQ_portfolio#31]
### 概要

---
#### MVP
- [ ] 新規登録
- [ ] ログイン
- [ ] パスワードリセット
- [ ] メールアドレス変更
- [ ] OpenAI APIによる、メッセージ提案
- [ ] LINE通知
- [ ] 連絡先登録

#### 本リリース
- [ ] 画像投稿
- [ ] マルチ検索
- [ ] カレンダー

---
### 必要なページ
- [ ] トップ
- [ ] 新規登録
- [ ] ログイン
- [ ] パスワードリセット申請
- [ ] 新しいパスワード入力
- [ ] マイページ
- [ ] メールアドレス、パスワード変更
- [ ] プライバシーポリシー
- [ ] 利用規約
- [ ] お問い合わせ
- [ ] ヘッダー
- [ ] フッター

#### AIメッセージ提案関連
- [ ] 導入
- [ ] 質問
- [ ] 文章提案

#### 連絡帳関連
- [ ] グループ一覧（本リリース対応）
- [ ] 連絡先一覧
- [ ] 連絡先詳細
- [ ] アルバム一覧（本リリース対応）
- [ ] アルバム詳細・編集（本リリース対応）
- [ ] メモ詳細・編集（本リリース対応）
- [ ] 通知設定

#### その他
- [ ] LINE友達登録
- [ ] カレンダー（本リリース対応）

---
### 補足
MVPまでの想定開発期間：ストーリーポイント７９×２時間＝１５８時間　１５８時間／６時間（１日）＝２７日

**Comment by shota-hope** [comment]
Projectsが公開になっていないようなので、見直していただき再提出をお願いします。
[![Image from Gyazo](https://i.gyazo.com/7ec3c207d3fe4768755467d35c619b41.png)](https://gyazo.com/7ec3c207d3fe4768755467d35c619b41)

**Comment by wassupdee** [comment]
大変失礼いたしました。
リポジトリとプロジェクトがLinkされていなかったようなので、Linkさせました。

こちらで確認できますでしょうか？どうぞよろしくお願い申し上げます。

[![Image from Gyazo](https://i.gyazo.com/c2cc95a6ace9123df7ca964281f1c336.png)](https://gyazo.com/c2cc95a6ace9123df7ca964281f1c336)

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
プロジェクト確認でしました。ありがとうございます。

---

以下、コメントになります。
ストーリーポイント8が２つあります。こちら8は大きいと思いますので、もうすこし調べて分けていただきたいです。
ストーリーポイント5も大きいと思いましたので、分けれる際は分けてみてください。

**Comment by wassupdee** [comment]
ご確認、ご指摘どうもありがとうございます。

ストーリーポイント８、及び５のIssueを分解いたしました。
（本リリース対応のIssueは、実装しない・実装方法の変更の可能性がある為、MVP完成後に精査させていただけたら幸いです）

以上、ご確認の程、どうぞよろしくお願い申し上げます。

**Comment by kenchasonakai** [comment]
LGTMです！

**Comment by wassupdee** [comment]
ご確認どうもありがとうございました！
